### ISSUE TITLE
ip-cmd: Detect timeout

### ISSUE THREAD

**Issue by Trikolon** [Trikolon/pbz-uber#21]

**Comment by Endebert** [comment]
@Trikolon also try to catch ERR_BLOCKED_BY_CLIENT exception, my adblock doesn't like ipinfo :)

![image](https://cloud.githubusercontent.com/assets/9431420/24042083/bf98f684-0b10-11e7-84c6-be3a09119bf7.png)

**Comment by Trikolon** [comment]
Thanks for the info! I'm also considering circumventing this issue: #8 
When it's all on the same domain there shouldn't be any problems.

**Comment by Trikolon** [comment]
Just fixed the error output. A name-conflict was causing 'console.error(msg)' to fail. Now it tells you that it failed ( at least)
